version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/todo-app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=lin4
      - MYSQL_DATABASE=todos
    command: sh -c "yarn install && yarn run dev"
    depends_on:
      - db
    networks:
      - todo-network

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=lin4
      - MYSQL_DATABASE=todos
    volumes:
      - todo-mysql-data:/var/lib/mysql
    networks:
      - todo-network

volumes:
  todo-mysql-data:

networks:
  todo-network:
    driver: bridge
